export const TEAM_ALIASES: Record<string, string> = {
  "76ers": "Philadelphia 76ers",
  "49ers": "San Francisco 49ers",
  afc: "AFC",
  ars: "Arsenal",
  arsenal: "Arsenal",
  "arsenal fc": "Arsenal",
  barca: "Barcelona",
  barcelona: "Barcelona",
  "barcelona fc": "Barcelona",
  "bayer leverkusen": "Bayer Leverkusen",
  "bayern munich": "Bayern Munich",
  "borussia dortmund": "Borussia Dortmund",
  "brighton and hove albion": "Brighton and Hove Albion",
  "brighton and hove albion fc": "Brighton and Hove Albion",
  "brighton hove albion": "Brighton and Hove Albion",
  brighton: "Brighton and Hove Albion",
  brentford: "Brentford",
  "brentford fc": "Brentford",
  bre: "Brentford",
  bucks: "Milwaukee Bucks",
  bulls: "Chicago Bulls",
  cavaliers: "Cleveland Cavaliers",
  cavs: "Cleveland Cavaliers",
  cle: "Cleveland Cavaliers",
  celtics: "Boston Celtics",
  chelsea: "Chelsea",
  "chelsea fc": "Chelsea",
  chiefs: "Kansas City Chiefs",
  clippers: "Los Angeles Clippers",
  cowboys: "Dallas Cowboys",
  cry: "Crystal Palace",
  "crystal palace": "Crystal Palace",
  "crystal palace fc": "Crystal Palace",
  dodgers: "Los Angeles Dodgers",
  eagles: "Philadelphia Eagles",
  heat: "Miami Heat",
  "inter milan": "Inter Milan",
  "inter milano": "Inter Milan",
  juventus: "Juventus",
  "juventus fc": "Juventus",
  knicks: "New York Knicks",
  lakers: "Los Angeles Lakers",
  lal: "Los Angeles Lakers",
  liv: "Liverpool",
  liverpool: "Liverpool",
  "liverpool fc": "Liverpool",
  "man city": "Manchester City",
  "manchester city": "Manchester City",
  "manchester city fc": "Manchester City",
  "man utd": "Manchester United",
  "man united": "Manchester United",
  "manchester united": "Manchester United",
  "manchester united fc": "Manchester United",
  mavericks: "Dallas Mavericks",
  milan: "AC Milan",
  "ac milan": "AC Milan",
  napoli: "Napoli",
  nets: "Brooklyn Nets",
  nuggets: "Denver Nuggets",
  "ny knicks": "New York Knicks",
  nyk: "New York Knicks",
  pacers: "Indiana Pacers",
  packers: "Green Bay Packers",
  psg: "Paris Saint-Germain",
  "paris saint germain": "Paris Saint-Germain",
  "paris saint-germain": "Paris Saint-Germain",
  "paris saint germain fc": "Paris Saint-Germain",
  "paris saint-germain fc": "Paris Saint-Germain",
  raptors: "Toronto Raptors",
  "real madrid": "Real Madrid",
  "real madrid cf": "Real Madrid",
  roma: "Roma",
  sixers: "Philadelphia 76ers",
  spurs: "Tottenham Hotspur",
  suns: "Phoenix Suns",
  okc: "Oklahoma City Thunder",
  thunder: "Oklahoma City Thunder",
  "tottenham hotspur": "Tottenham Hotspur",
  "tottenham hotspur fc": "Tottenham Hotspur",
  tottenham: "Tottenham Hotspur",
  warriors: "Golden State Warriors",
  yankees: "New York Yankees",
};

export const TEAM_SUFFIX_PATTERN = /\b(?:fc|afc|cf|sc|club|football club|basketball club)\b/gi;
